export interface WebPackage {
  slug: string;
  title: string;
  emoji: string;
  shortDesc: string;
  price: string;
  priceNumber: number;
  badge?: string;
  badgeColor: string;
  gradient: string;
  popular?: boolean;
  forWho: string;
  whatsIncluded: string[];
  pages: string[];
  features: string[];
  support: string;
}

export const webPackages: WebPackage[] = [
  {
    slug: "online-store",
    title: "Online Store with Admin Panel",
    emoji: "🛒",
    shortDesc:
      "Complete online store with admin panel to manage products, orders, and customers yourself.",
    price: "PKR 5,000",
    priceNumber: 5000,
    badge: "Most Popular",
    badgeColor: "#6366f1",
    gradient: "from-[#6366f1] to-[#8b5cf6]",
    popular: true,
    forWho:
      "Businesses that want full control to add/edit products and view orders themselves.",
    whatsIncluded: [
      "Custom-built online store",
      "Admin panel (you manage everything)",
      "Product catalog with categories",
      "WhatsApp ordering integration",
      "1 year free hosting",
      "Google Business listing",
      "Basic SEO on all pages",
      "Mobile responsive design",
      "Meta Pixel installation",
      "3 months support & management",
    ],
    pages: [
      "Home Page",
      "Product Listing",
      "Individual Product Pages",
      "Categories Page",
      "About Page",
      "Contact Page",
      "Admin Dashboard",
    ],
    features: [
      "Add/edit products from admin",
      "View customer orders",
      "Manage product inventory",
      "Upload product images",
      "Update prices instantly",
      "WhatsApp order notifications",
    ],
    support: "3 months full support included",
  },
  {
    slug: "portfolio",
    title: "Portfolio Website",
    emoji: "🎨",
    shortDesc:
      "Professional portfolio to showcase your work, skills, and services. Perfect for freelancers and creatives.",
    price: "PKR 5,000",
    priceNumber: 5000,
    badgeColor: "#8b5cf6",
    gradient: "from-[#8b5cf6] to-[#a78bfa]",
    forWho:
      "Freelancers, photographers, designers, artists, writers, consultants.",
    whatsIncluded: [
      "Custom portfolio design",
      "Project showcase gallery",
      "About me section",
      "Services list",
      "Contact form",
      "1 year free hosting",
      "Basic SEO",
      "Mobile responsive",
      "Social media links",
      "3 months support",
    ],
    pages: [
      "Home / Hero Page",
      "About Me",
      "Portfolio / Projects",
      "Services",
      "Contact",
    ],
    features: [
      "Beautiful project gallery",
      "Testimonials section",
      "Skills showcase",
      "Downloadable CV/resume",
      "Direct WhatsApp contact",
      "Social proof section",
    ],
    support: "3 months support included",
  },
  {
    slug: "landing-page",
    title: "Landing Page",
    emoji: "🎯",
    shortDesc:
      "Single high-converting page designed to capture leads or sell one specific product. Perfect for Meta ads.",
    price: "PKR 5,000",
    priceNumber: 5000,
    badgeColor: "#f97316",
    gradient: "from-[#f97316] to-[#fb923c]",
    forWho:
      "Businesses running Meta/Google ads, product launches, lead generation campaigns.",
    whatsIncluded: [
      "Custom landing page design",
      "Conversion-focused layout",
      "Lead capture form",
      "WhatsApp button",
      "Meta Pixel integration",
      "Fast loading (<2s)",
      "Mobile optimized",
      "1 year free hosting",
      "Basic SEO",
      "3 months support",
    ],
    pages: ["Single Landing Page (Long-form)"],
    features: [
      "Hero section with strong CTA",
      "Benefits & features section",
      "Customer testimonials",
      "FAQ section",
      "Lead capture form",
      "Meta Pixel for ad tracking",
    ],
    support: "3 months support included",
  },
  {
    slug: "ecommerce",
    title: "E-Commerce Website",
    emoji: "🛍️",
    shortDesc:
      "Full-featured online store for businesses with 20+ products. Includes shopping cart and order management.",
    price: "PKR 5,000",
    priceNumber: 5000,
    badgeColor: "#06b6d4",
    gradient: "from-[#06b6d4] to-[#22d3ee]",
    forWho:
      "Businesses with large product catalogs (clothing brands, electronics, accessories).",
    whatsIncluded: [
      "Full e-commerce website",
      "Shopping cart functionality",
      "WhatsApp checkout",
      "Multiple payment options info",
      "Product categories",
      "Search & filter",
      "1 year free hosting",
      "Google Business listing",
      "SEO for all products",
      "3 months support",
    ],
    pages: [
      "Home Page",
      "Shop / Product Listing",
      "Product Detail Pages",
      "Categories",
      "Cart Page",
      "Checkout Page",
      "About Page",
      "Contact Page",
    ],
    features: [
      "Shopping cart with multiple items",
      "Order via WhatsApp/Email",
      "Product variants (size, color)",
      "Search and filter products",
      "Featured products section",
      "Customer reviews on products",
    ],
    support: "3 months support included",
  },
  {
    slug: "restaurant",
    title: "Restaurant Website",
    emoji: "🍽️",
    shortDesc:
      "Beautiful restaurant website with menu, food gallery, WhatsApp ordering, and Google Maps integration.",
    price: "PKR 5,000",
    priceNumber: 5000,
    badgeColor: "#ef4444",
    gradient: "from-[#ef4444] to-[#f87171]",
    forWho:
      "Restaurants, cafes, food trucks, catering businesses, dhabas, bakeries selling food.",
    whatsIncluded: [
      "Restaurant-themed design",
      "Digital food menu",
      "Food photo gallery",
      "WhatsApp ordering",
      "Google Maps location",
      "Opening hours display",
      "1 year free hosting",
      "Google Business listing",
      "Local SEO",
      "3 months support",
    ],
    pages: [
      "Home Page (Hero with food)",
      "Menu Page",
      "Photo Gallery",
      "About Us",
      "Reservations / Order",
      "Contact & Location",
    ],
    features: [
      "Beautiful menu with categories",
      "High-quality food gallery",
      "WhatsApp order button",
      "Google Maps embedded",
      "Special offers section",
      "Reviews/testimonials",
    ],
    support: "3 months support included",
  },
  {
    slug: "hotel",
    title: "Hotel Website",
    emoji: "🏨",
    shortDesc:
      "Premium hotel website with rooms, amenities, booking inquiries, and beautiful gallery.",
    price: "PKR 5,000",
    priceNumber: 5000,
    badgeColor: "#0ea5e9",
    gradient: "from-[#0ea5e9] to-[#38bdf8]",
    forWho:
      "Hotels, guest houses, resorts, hostels, vacation rentals in Pakistan.",
    whatsIncluded: [
      "Luxury hotel design",
      "Rooms showcase pages",
      "Amenities section",
      "Photo gallery",
      "Booking inquiry form",
      "WhatsApp booking",
      "Google Maps",
      "1 year free hosting",
      "Local SEO",
      "3 months support",
    ],
    pages: [
      "Home Page",
      "Rooms / Suites",
      "Amenities & Services",
      "Photo Gallery",
      "Booking",
      "About Hotel",
      "Contact & Directions",
    ],
    features: [
      "Beautiful room showcases",
      "Room availability info",
      "Pricing per room type",
      "Amenities highlights",
      "Location and nearby attractions",
      "WhatsApp booking inquiry",
    ],
    support: "3 months support included",
  },
  {
    slug: "hospital",
    title: "Hospital / Clinic Website",
    emoji: "🏥",
    shortDesc:
      "Professional medical website with doctors profiles, departments, services, and appointment booking.",
    price: "PKR 5,000",
    priceNumber: 5000,
    badgeColor: "#10b981",
    gradient: "from-[#10b981] to-[#34d399]",
    forWho:
      "Hospitals, clinics, medical centers, dental offices, specialist doctors.",
    whatsIncluded: [
      "Professional medical design",
      "Doctor profiles",
      "Department/services list",
      "WhatsApp appointment booking",
      "Google Maps location",
      "Opening hours",
      "1 year free hosting",
      "Google Business listing",
      "Local SEO",
      "3 months support",
    ],
    pages: [
      "Home Page",
      "About Hospital",
      "Doctors",
      "Departments / Services",
      "Appointments",
      "Contact & Location",
    ],
    features: [
      "Doctor profile pages",
      "Department/specialty list",
      "Service descriptions",
      "Appointment booking",
      "Emergency contact info",
      "Patient testimonials",
    ],
    support: "3 months support included",
  },
  {
    slug: "bakery",
    title: "Bakery Website",
    emoji: "🧁",
    shortDesc:
      "Sweet bakery website with product showcase, custom order options, and WhatsApp ordering.",
    price: "PKR 5,000",
    priceNumber: 5000,
    badgeColor: "#ec4899",
    gradient: "from-[#ec4899] to-[#f472b6]",
    forWho:
      "Bakeries, cake shops, dessert shops, home-based bakers, sweet shops.",
    whatsIncluded: [
      "Sweet bakery design",
      "Product showcase (cakes, pastries)",
      "Custom order form",
      "Photo gallery",
      "WhatsApp ordering",
      "Google Maps",
      "1 year free hosting",
      "Local SEO",
      "Google Business listing",
      "3 months support",
    ],
    pages: [
      "Home Page",
      "Product Catalog",
      "Custom Orders / Cakes",
      "Gallery",
      "About Us",
      "Contact & Order",
    ],
    features: [
      "Beautiful product display",
      "Custom cake order form",
      "Flavor & size options",
      "Gallery of past creations",
      "Delivery area info",
      "Bulk order discounts",
    ],
    support: "3 months support included",
  },
  {
    slug: "school",
    title: "School / Academy Website",
    emoji: "🏫",
    shortDesc:
      "Educational website with admissions info, faculty profiles, programs, and notices section.",
    price: "PKR 5,000",
    priceNumber: 5000,
    badgeColor: "#f59e0b",
    gradient: "from-[#f59e0b] to-[#fbbf24]",
    forWho:
      "Schools, academies, tuition centers, training institutes, coaching centers.",
    whatsIncluded: [
      "Educational design",
      "Admissions section",
      "Faculty profiles",
      "Programs/courses list",
      "Notice board",
      "Photo gallery",
      "1 year free hosting",
      "Google Business listing",
      "Local SEO",
      "3 months support",
    ],
    pages: [
      "Home Page",
      "About School",
      "Programs / Courses",
      "Faculty",
      "Admissions",
      "Notices / Events",
      "Gallery",
      "Contact",
    ],
    features: [
      "Admissions information",
      "Class schedules",
      "Teacher profiles",
      "Notice board for parents",
      "Photo gallery of events",
      "Fee structure section",
    ],
    support: "3 months support included",
  },
  {
    slug: "gym",
    title: "Gym / Fitness Website",
    emoji: "💪",
    shortDesc:
      "Energetic fitness website with class schedules, trainers, membership plans, and contact.",
    price: "PKR 5,000",
    priceNumber: 5000,
    badgeColor: "#dc2626",
    gradient: "from-[#dc2626] to-[#ef4444]",
    forWho:
      "Gyms, fitness centers, yoga studios, CrossFit boxes, personal trainers.",
    whatsIncluded: [
      "Energetic gym design",
      "Membership plans display",
      "Class schedule",
      "Trainer profiles",
      "Photo gallery",
      "Free trial signup",
      "1 year free hosting",
      "Google Business listing",
      "Local SEO",
      "3 months support",
    ],
    pages: [
      "Home Page",
      "About Us",
      "Membership Plans",
      "Classes / Programs",
      "Trainers",
      "Schedule",
      "Free Trial",
      "Contact",
    ],
    features: [
      "Class schedule grid",
      "Trainer profiles with specialties",
      "Membership pricing",
      "Free trial booking",
      "Gym facility gallery",
      "Member testimonials",
    ],
    support: "3 months support included",
  },
  {
    slug: "salon",
    title: "Salon / Beauty Parlor Website",
    emoji: "💅",
    shortDesc:
      "Elegant salon website with services menu, price list, before/after gallery, and WhatsApp booking.",
    price: "PKR 5,000",
    priceNumber: 5000,
    badgeColor: "#a855f7",
    gradient: "from-[#a855f7] to-[#c084fc]",
    forWho:
      "Beauty salons, parlors, spas, nail salons, hair salons, home-based beauticians.",
    whatsIncluded: [
      "Elegant salon design",
      "Services with prices",
      "Before/after gallery",
      "WhatsApp booking",
      "Google Maps",
      "Opening hours",
      "1 year free hosting",
      "Google Business listing",
      "Local SEO",
      "3 months support",
    ],
    pages: [
      "Home Page",
      "Services & Pricing",
      "Gallery (Before/After)",
      "About Us",
      "Booking",
      "Contact & Location",
    ],
    features: [
      "Service menu with prices",
      "Before/after photo gallery",
      "WhatsApp appointment booking",
      "Special offers section",
      "Stylist profiles",
      "Customer reviews",
    ],
    support: "3 months support included",
  },
  {
    slug: "real-estate",
    title: "Real Estate Website",
    emoji: "🏠",
    shortDesc:
      "Property website with listings, photo galleries, location maps, and WhatsApp inquiries.",
    price: "PKR 5,000",
    priceNumber: 5000,
    badgeColor: "#14b8a6",
    gradient: "from-[#14b8a6] to-[#2dd4bf]",
    forWho:
      "Real estate agents, property dealers, builders, developers, plot dealers.",
    whatsIncluded: [
      "Real estate design",
      "Property listings",
      "Property photo galleries",
      "Google Maps per property",
      "WhatsApp inquiries",
      "Category filters",
      "1 year free hosting",
      "Google Business listing",
      "Local SEO",
      "3 months support",
    ],
    pages: [
      "Home Page",
      "Property Listings",
      "Individual Property Pages",
      "Categories (Plots, Houses, etc.)",
      "About Us",
      "Contact",
    ],
    features: [
      "Property cards with photos",
      "Detailed property pages",
      "Price and size info",
      "Google Maps location",
      "WhatsApp inquiry button",
      "Mark as Sold/Available",
    ],
    support: "3 months support included",
  },
];